"""empty message

Revision ID: 4ad687b0eecb
Revises: 
Create Date: 2022-07-06 20:49:34.466313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad687b0eecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid'),
    mysql_collate='utf8mb4_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
