"""empty message

Revision ID: a74154e5bd83
Revises: 4ad687b0eecb
Create Date: 2022-07-06 21:13:27.339683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74154e5bd83'
down_revision = '4ad687b0eecb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round', sa.JSON(), nullable=True),
    sa.Column('robot', sa.SMALLINT(), nullable=True),
    sa.Column('last_modified', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
